language: R
sudo: false
cache: packages
os:
  - linux
  - osx
before_script:
- Rscript ci.R
after_success:
- ./.trigger.sh
- Rscript -e 'covr::codecov()'
notifications:
  email: false
  slack:
    secure: A74a1I9I9YbgASeeuQKcaqLE5w18BhpHJXngheGao6A9/M3woStdHD23fYzyZMplcl7HRIEJCjVqxNGVOIpylWYv3vHc6KMj/utMw5K3/jEipVvt9L62Ww2zXT17Hlb2N0W1BBja8YAwivq/pn1z5vPYt8gS5SmU+/NsZdalJdbgxC8Fa679O5dIKHBtZIyO8l+xXUdMFQgTGaSS9EKEalDNILyzCTqBh9a1n6Tj8+hGO1pG1nZgGo3lDS6WQQDmsiIb7qlwboMgFfWLilce4coLnrl5Hu8O8W4jnJDaLCdjtxHNkt9EYA89HVY3n13RaNZN1jwXfc4Ntr0icEBLZPWKMRErYPTt2M48syhOv8GBsDVgKP/WHa8dYAXvUcucumD2ERcEzdeYsWtYcsV+IA3MEFq2mN4OsZcTdkTrdkyNL04AsZ1vkH6IaHvRgyB3jUu8BZ730bQLhI6x5YGhN6FaDYmL9wuKLt9tu2xDBItp2ZyzSlV9gGnyDxG6stviT0uw7ZbQjnrXWxyNxigbDgMxDB8GNwXU+Wm91pg4mp0yx5jrb076g3GXDJTHN6c7DdWa01KejNJGVBVngJ6RciQeLDw0t4R5Azfw3vhi3S16mklz+uVqlIoJyJUPiSGYA1y0hupoD8e41MuV6f9aDtzMfRRmQM4lIUmT5lfxQng=
